version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      - ../models:/app/models
    restart: unless-stopped
    container_name: defi-trading-bot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
