version: '3.8'

services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
    restart: unless-stopped
    container_name: defi-trading-bot
